export ZSH=$HOME/.config/shell/zsh/oh-my-zsh
ZSH_THEME="owntheme"
source $ZSH/oh-my-zsh.sh
[[ $OS == 'darwin' ]] && OS=osx
[[ -f plugins/$OS/$OS.plugin.zsh ]] && source plugins/$OS/$OS.plugin.zsh
for src in $HOME/.config/shell/*; do
  [[ ! -d $src ]] && [[ $src != $HOME/.config/shell/$ZSH_THEME.zsh-theme ]] && source $src
done
